#!/usr/bin/env bash
# memory-index.sh — Build a concept→file index from memory files
# Designed for fast grep lookups to answer "when/where/who" questions
# Usage: scripts/memory-index.sh [--quiet]
#
# Scans workspace memory files and builds a greppable index organized by:
# - Topics (configurable keyword categories)
# - Timeline (recent daily summaries)
# - Key data files
#
# Configure topic categories by editing the CATEGORIES array below.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

detect_workspace() {
  if [[ -n "${IRONCLAD_WORKSPACE:-}" ]]; then
    echo "$IRONCLAD_WORKSPACE"
    return
  fi
  local dir
  dir="$(cd "$SCRIPT_DIR/.." && pwd)"
  if [[ -d "$dir/.ironclad" ]]; then echo "$dir"; return; fi
  local check="$dir"
  while [[ "$check" != "/" ]]; do
    if [[ -d "$check/.ironclad" ]]; then echo "$check"; return; fi
    check="$(dirname "$check")"
  done
  check="$(pwd)"
  while [[ "$check" != "/" ]]; do
    if [[ -d "$check/.ironclad" ]]; then echo "$check"; return; fi
    check="$(dirname "$check")"
  done
  echo "$dir"
}

WORKSPACE="$(detect_workspace)"
OUTPUT="$WORKSPACE/data/memory-index.md"
MEMORY_DIR="${IRONCLAD_MEMORY_DIR:-$WORKSPACE/memory}"
DATA_DIR="$WORKSPACE/data"
MEMORY_FILE="$WORKSPACE/MEMORY.md"
QUIET=false

[[ "${1:-}" == "--quiet" ]] && QUIET=true

mkdir -p "$(dirname "$OUTPUT")"

# Temp file for building index
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

cat > "$TMP" << 'HEADER'
# Memory Index
> Auto-generated by memory-index.sh. Last updated: TIMESTAMP
> Use: `grep -i "keyword" data/memory-index.md` to find which files contain what.

HEADER

sed -i '' "s/TIMESTAMP/$(date '+%Y-%m-%d %H:%M %Z')/" "$TMP" 2>/dev/null \
  || sed -i "s/TIMESTAMP/$(date '+%Y-%m-%d %H:%M %Z')/" "$TMP"

# ============================================================================
# TOPIC CATEGORIES
# Edit these to match your workspace content. Each entry is "category|keyword".
# The index will search memory files for each keyword and list matching files.
# ============================================================================

# Define categories and their keywords as arrays
# Format: category_name:keyword1,keyword2,keyword3
CATEGORIES=(
  "People:team,manager,client,vendor,partner,contractor"
  "Projects:project,milestone,deadline,launch,release,deploy"
  "Systems:server,database,API,deployment,infrastructure,monitoring"
  "Financial:budget,expense,invoice,payment,subscription,cost"
  "Decisions:decided,approved,rejected,agreed,committed,policy"
)

# --- Topic Index ---
for category_entry in "${CATEGORIES[@]}"; do
  category="${category_entry%%:*}"
  keywords_str="${category_entry#*:}"
  IFS=',' read -ra keywords <<< "$keywords_str"

  echo "## $category" >> "$TMP"

  for keyword in "${keywords[@]}"; do
    # Search memory files and data files
    search_dirs=()
    [[ -d "$MEMORY_DIR" ]] && search_dirs+=("$MEMORY_DIR"/*)
    [[ -f "$MEMORY_FILE" ]] && search_dirs+=("$MEMORY_FILE")

    hits=$(grep -ril "$keyword" "${search_dirs[@]}" 2>/dev/null | sort -r | head -10 || true)
    if [[ -n "$hits" ]]; then
      echo "### $keyword" >> "$TMP"
      while IFS= read -r f; do
        rel="${f#$WORKSPACE/}"
        ctx=$(grep -im1 "$keyword" "$f" 2>/dev/null | head -c 120 || true)
        echo "- \`$rel\`: $ctx" >> "$TMP"
      done <<< "$hits"
      echo "" >> "$TMP"
    fi
  done
done

# --- Timeline (reverse chronological from daily files) ---
echo "## Timeline (Recent Daily Summaries)" >> "$TMP"
if [[ -d "$MEMORY_DIR" ]]; then
  for f in $(ls -r "$MEMORY_DIR"/*.md 2>/dev/null | head -14); do
    rel="${f#$WORKSPACE/}"
    date_str=$(basename "$f" .md)
    # Extract first 3 non-empty, non-header lines as summary
    summary=$(grep -v '^#\|^$\|^---\|^>\|^- *$' "$f" 2>/dev/null | head -3 | tr '\n' ' ' | head -c 200 || true)
    echo "### $date_str" >> "$TMP"
    echo "- \`$rel\`: $summary" >> "$TMP"
    # Extract key events
    grep -E '^\s*-\s+.*(done|completed|fixed|sent|created|deployed|built|shipped|broke|failed|updated|installed)' "$f" 2>/dev/null | head -5 | while IFS= read -r line; do
      echo "  $line" >> "$TMP"
    done
    echo "" >> "$TMP"
  done
fi

# --- Key Data Files ---
echo "## Key Data Files" >> "$TMP"
echo "Structured data locations found in workspace:" >> "$TMP"
echo "" >> "$TMP"

if [[ -d "$DATA_DIR" ]]; then
  find "$DATA_DIR" -maxdepth 2 \( -name '*.json' -o -name '*.md' \) -type f 2>/dev/null | sort | while IFS= read -r df; do
    rel="${df#$WORKSPACE/}"
    # Extract first meaningful line as description
    desc=$(head -5 "$df" 2>/dev/null | grep -v '^[{[]$\|^$\|^---$' | head -1 | head -c 80 || true)
    echo "- \`$rel\` — $desc" >> "$TMP"
  done
fi

echo "" >> "$TMP"
echo "---" >> "$TMP"

# Count files
memory_count=$(ls "$MEMORY_DIR"/*.md 2>/dev/null | wc -l | tr -d ' ' || echo 0)
data_count=$(find "$DATA_DIR" -name '*.md' -o -name '*.json' 2>/dev/null | wc -l | tr -d ' ' || echo 0)
echo "*Index covers: ${memory_count} daily memory files, MEMORY.md, and ${data_count} data files.*" >> "$TMP"

mv "$TMP" "$OUTPUT"
$QUIET || echo "Memory index written to $OUTPUT ($(wc -l < "$OUTPUT" | tr -d ' ') lines)"
